build.gradle
src/main/java/io/temporal/samples/bookingsaga/TripBookingWorkflowImpl.java
src/main/java/io/temporal/samples/common/QueryWorkflowExecution.java
src/main/java/io/temporal/samples/fileprocessing/StoreActivities.java
src/main/java/io/temporal/samples/hello/HelloActivityRetry.java
src/main/java/io/temporal/samples/hello/HelloAsyncActivityCompletion.java
src/main/java/io/temporal/samples/hello/HelloCron.java
src/main/java/io/temporal/samples/hello/HelloPeriodic.java
src/main/java/io/temporal/samples/hello/HelloSearchAttributes.java
src/main/java/io/temporal/samples/moneytransfer/AccountImpl.java
src/main/java/io/temporal/samples/moneytransfer/AccountTransferWorkflowImpl.java
src/main/java/io/temporal/samples/updatabletimer/DynamicSleepWorkflowStarter.java
src/main/resources/logback.xml
src/test/java/io/temporal/samples/bookingsaga/TripBookingWorkflowTest.java
src/test/java/io/temporal/samples/fileprocessing/FileProcessingTest.java
src/test/java/io/temporal/samples/hello/HelloCronTest.java
src/test/java/io/temporal/samples/hello/HelloExceptionTest.java
src/test/java/io/temporal/samples/hello/HelloPeriodicTest.java
src/test/java/io/temporal/samples/hello/HelloSignalTest.java

Merging changes from develop updating temporal-sdk dependency to v0.25.0.

25.0 Release

---

.buildkite/pipeline.yml
docker/buildkite/Dockerfile
docker/buildkite/README.md
docker/buildkite/docker-compose.yaml

This PR adds files required for the automated buildkite build.

Add buildkite configuration for automated builds on github

---

build.gradle

Use latest 1.0.4 release in samples.

Use 1.0.4 release

---

build.gradle
src/main/java/io/temporal/samples/ssl/SslEnabledWorker.java

Shows how to setup SSL enabled worker.
Also adds a dependency on recently added testing library.

Sample for configuring SSL enabled worker

---

build.gradle

Updating to the latest release.

Update to 1.0.6 release

---

build.gradle

Update SDK to 1.0.7

---

README.md

Fixes the instructions for the 'Run Temporal Server' section in main readme
The current instructions are not correct

Fix the 'Run Temporal Server' section instructions

---

src/main/java/io/temporal/samples/hello/HelloActivity.java
src/main/java/io/temporal/samples/hello/HelloActivityRetry.java
src/main/java/io/temporal/samples/hello/HelloAsync.java
src/main/java/io/temporal/samples/hello/HelloAsyncActivityCompletion.java
src/main/java/io/temporal/samples/hello/HelloAsyncLambda.java
src/main/java/io/temporal/samples/hello/HelloCancellationScope.java
src/main/java/io/temporal/samples/hello/HelloChild.java
src/main/java/io/temporal/samples/hello/HelloCron.java
src/main/java/io/temporal/samples/hello/HelloException.java
src/main/java/io/temporal/samples/hello/HelloPeriodic.java
src/main/java/io/temporal/samples/hello/HelloPolymorphicActivity.java
src/main/java/io/temporal/samples/hello/HelloQuery.java
src/main/java/io/temporal/samples/hello/HelloSaga.java
src/main/java/io/temporal/samples/hello/HelloSearchAttributes.java
src/main/java/io/temporal/samples/hello/HelloSignal.java
src/main/java/io/temporal/samples/moneytransfer/AccountActivityWorker.java
src/main/java/io/temporal/samples/moneytransfer/TransferRequester.java
src/main/java/io/temporal/samples/ssl/SslEnabledWorker.java
src/test/java/io/temporal/samples/hello/HelloCronTest.java
src/test/java/io/temporal/samples/hello/HelloPeriodicTest.java

1) Added comments and descriptions to all of the hello examples
2) Updates examples to all include a workflow id
3) made some small updates to examples
When I was first learning about Temporal these examples were the first thing I looked at. 
I wanted to add these changes to make it easier for people that learn from them as well
to be able to easier understand the code.

Update hello samples

---

README.md
build.gradle
src/main/java/io/temporal/samples/hello/HelloActivityExclusiveChoice.java
src/test/java/io/temporal/samples/hello/HelloActivityExclusiveChoiceTest.java

Adding a simple example that shows how to call different activities based on dynamic input.
Kinda equivalent to Go SDK example: https://github.com/temporalio/samples-go/tree/master/choice-exclusive
Wanted to add more simple examples for new users

Adding HelloActivityExclusiveChoice example

---

README.md

Link in README has changed.
Page URL in docs has changed.
N/A
N/A
N/A

Updating link to docs in README

---

src/main/java/io/temporal/samples/hello/HelloSearchAttributes.java

Updated HelloSearchAttributes:
* added comments
* added comments
* small updates to code
This example had comments that it is not functional, but the fix has already been applied to the java sdk
Updating example so that is clear to users

Updated HelloSearchAttributes example

---

README.md
src/main/java/io/temporal/samples/hello/HelloSideEffect.java
src/test/java/io/temporal/samples/hello/HelloSideEffectTest.java

Adding SideEffect Example
Example did not exist

Adding SideEffect example

---

.buildkite/pipeline.yml
docker/buildkite/Dockerfile
docker/buildkite/docker-compose.yaml

Added fossa scans to buildkite
Add license checks
N/A
buildkite
N/A

Add fossa scans

---

README.md
src/main/java/io/temporal/samples/hello/HelloLocalActivity.java
src/test/java/io/temporal/samples/hello/HelloLocalActivityTest.java

Added an example to demonstrate local activity
This example was missing in the docs and it was not very much clear how to code.
NA
NA
Added new unit test
Readme updated

Add hello world example for local activity

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/io/temporal/samples/hello/HelloLocalActivity.java
src/test/java/io/temporal/samples/fileprocessing/FileProcessingTest.java
src/test/java/io/temporal/samples/hello/HelloAsyncActivityCompletionTest.java
src/test/java/io/temporal/samples/hello/HelloAsyncLambdaTest.java
src/test/java/io/temporal/samples/hello/HelloAsyncTest.java
src/test/java/io/temporal/samples/hello/HelloCronTest.java
src/test/java/io/temporal/samples/hello/HelloPeriodicTest.java

Update to Java SDK 1.0.9

---

src/main/java/io/temporal/samples/encryptedpayloads/CryptDataConverter.java

Small fix for unused variable warning during compile 

Small fix for unused var warning

---

README.md
src/main/java/io/temporal/samples/hello/HelloParallelActivity.java
src/test/java/io/temporal/samples/hello/HelloParallelActivityTest.java

Adding async parallel activity example
Was missing 
1. Closes 

Adding Parallel Async Activity Sample

---

README.md
src/main/java/io/temporal/samples/hello/HelloDynamic.java
src/test/java/io/temporal/samples/hello/HelloDynamicTest.java

* Adding sample that shows the use of DynamicWorkflow and DynamicActivity Interfaces
Its not currently available
1. Closes 

Adding DynamicWorkflow and DynamicActivity sample

---

README.md
src/main/java/io/temporal/samples/hello/HelloDetachedCancellationScope.java
src/test/java/io/temporal/samples/hello/HelloDetachedCancellationScopeTest.java

Adding new sample which shows how to perform cleanup code if a workflow was cancelled
it was not available
1. Closes 

Detached Cancellation Scope Sample

---

src/main/java/io/temporal/samples/hello/HelloActivity.java
src/main/java/io/temporal/samples/hello/HelloActivityExclusiveChoice.java
src/main/java/io/temporal/samples/hello/HelloActivityRetry.java
src/main/java/io/temporal/samples/hello/HelloAsync.java
src/main/java/io/temporal/samples/hello/HelloAsyncActivityCompletion.java
src/main/java/io/temporal/samples/hello/HelloAsyncLambda.java
src/main/java/io/temporal/samples/hello/HelloCancellationScope.java
src/main/java/io/temporal/samples/hello/HelloChild.java
src/main/java/io/temporal/samples/hello/HelloCron.java
src/main/java/io/temporal/samples/hello/HelloDetachedCancellationScope.java
src/main/java/io/temporal/samples/hello/HelloDynamic.java
src/main/java/io/temporal/samples/hello/HelloException.java
src/main/java/io/temporal/samples/hello/HelloLocalActivity.java
src/main/java/io/temporal/samples/hello/HelloParallelActivity.java
src/main/java/io/temporal/samples/hello/HelloPeriodic.java
src/main/java/io/temporal/samples/hello/HelloPolymorphicActivity.java
src/main/java/io/temporal/samples/hello/HelloQuery.java
src/main/java/io/temporal/samples/hello/HelloSaga.java
src/main/java/io/temporal/samples/hello/HelloSearchAttributes.java
src/main/java/io/temporal/samples/hello/HelloSideEffect.java
src/main/java/io/temporal/samples/hello/HelloSignal.java

Fix samples comments

---

README.md
src/main/java/io/temporal/samples/bookingsaga/README.md
src/main/java/io/temporal/samples/fileprocessing/README.md
src/main/java/io/temporal/samples/hello/README.md
src/main/java/io/temporal/samples/interceptor/README.md
src/main/java/io/temporal/samples/moneybatch/README.md
src/main/java/io/temporal/samples/moneytransfer/README.MD
src/main/java/io/temporal/samples/updatabletimer/README.md

Snipsync comment wrapper has been added to the samples directory section of the README
To use the directory directly in the docs
1. Closes 
N/A
N/A
N/A

Adding snipsync comment wrapper to samples directory section of readme

---

build.gradle

Update to Java SDK 1.1.0
New SDK release
1. Closes 

Update Java SDK to 1.1.0

---

build.gradle
src/main/java/io/temporal/samples/fileprocessing/FileProcessingWorkflowImpl.java
src/main/java/io/temporal/samples/hello/HelloActivityRetry.java
src/main/java/io/temporal/samples/hello/HelloDynamic.java
src/test/java/io/temporal/samples/bookingsaga/TripBookingWorkflowTest.java
src/test/java/io/temporal/samples/fileprocessing/FileProcessingTest.java
src/test/java/io/temporal/samples/hello/HelloActivityExclusiveChoiceTest.java
src/test/java/io/temporal/samples/hello/HelloActivityRetryTest.java
src/test/java/io/temporal/samples/hello/HelloActivityTest.java
src/test/java/io/temporal/samples/hello/HelloAsyncActivityCompletionTest.java
src/test/java/io/temporal/samples/hello/HelloAsyncLambdaTest.java
src/test/java/io/temporal/samples/hello/HelloAsyncTest.java
src/test/java/io/temporal/samples/hello/HelloCancellationScopeTest.java
src/test/java/io/temporal/samples/hello/HelloChildTest.java
src/test/java/io/temporal/samples/hello/HelloCronTest.java
src/test/java/io/temporal/samples/hello/HelloDetachedCancellationScopeTest.java
src/test/java/io/temporal/samples/hello/HelloDynamicTest.java
src/test/java/io/temporal/samples/hello/HelloExceptionTest.java
src/test/java/io/temporal/samples/hello/HelloLocalActivityTest.java
src/test/java/io/temporal/samples/hello/HelloParallelActivityTest.java
src/test/java/io/temporal/samples/hello/HelloPeriodicTest.java
src/test/java/io/temporal/samples/hello/HelloPolymorphicActivityTest.java
src/test/java/io/temporal/samples/hello/HelloQueryTest.java
src/test/java/io/temporal/samples/hello/HelloSideEffectTest.java
src/test/java/io/temporal/samples/hello/HelloSignalTest.java
src/test/java/io/temporal/samples/interceptor/CountInterceptorTest.java
src/test/java/io/temporal/samples/moneybatch/TransferWorkflowTest.java
src/test/java/io/temporal/samples/moneytransfer/TransferWorkflowTest.java

Updated all tests to use WorkflowRule 
1. Closes 

Changing tests to use WorkflowRule

---

README.md
src/main/java/io/temporal/samples/listworkflows/Customer.java
src/main/java/io/temporal/samples/listworkflows/CustomerActivities.java
src/main/java/io/temporal/samples/listworkflows/CustomerActivitiesImpl.java
src/main/java/io/temporal/samples/listworkflows/CustomerWorkflow.java
src/main/java/io/temporal/samples/listworkflows/CustomerWorkflowImpl.java
src/main/java/io/temporal/samples/listworkflows/README.md
src/main/java/io/temporal/samples/listworkflows/Starter.java
src/test/java/io/temporal/samples/listworkflows/ListWorkflowsTest.java

Added a new "listworkflow" sample which shows how to set custom search attributes and then use
ListWorkflowExecutionsRequest to list them based on custom queries
This sample did not exist
1. Closes 

List workflows by custom attributes queries

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/io/temporal/samples/listworkflows/CustomerActivitiesImpl.java
src/main/java/io/temporal/samples/listworkflows/Starter.java
src/test/java/io/temporal/samples/hello/HelloCancellationScopeTest.java
src/test/java/io/temporal/samples/listworkflows/ListWorkflowsTest.java

Fixed InterruptedException handling and test timing issue
Broken build

Dependency updates. Timer bug + warning fix.

---

README.md
build.gradle
src/main/java/io/temporal/samples/payloadconverter/CEWorkflow.java
src/main/java/io/temporal/samples/payloadconverter/CEWorkflowImpl.java
src/main/java/io/temporal/samples/payloadconverter/CloudEventsPayloadConverter.java
src/main/java/io/temporal/samples/payloadconverter/README.md
src/main/java/io/temporal/samples/payloadconverter/Starter.java
src/test/java/io/temporal/samples/payloadconverter/PayloadConverterTest.java

Adds a custom payload converter sample
There wasn't one available
1. Closes 

Adding custom payload converter sample

---

src/main/java/io/temporal/samples/terminateworkflow/Starter.java

Just small formatting fix that's done via the formatting plugin during build

Small formatting update

---

build.gradle

Updating to the latest java sdk.

Update temporal sdk to 1.3.0

---

src/main/java/io/temporal/samples/dsl/DynamicDslWorkflow.java

Updated a comment on the DSL sample

Updating comment for DSL sample

---

src/main/java/io/temporal/samples/dsl/DynamicDslWorkflow.java

Another fix for the DSL sample comments to make it clear + fixed typo

Fix for DSL sample comments

---

src/main/java/io/temporal/samples/dsl/DynamicDslWorkflow.java
src/main/resources/dsl/customerapplication.json
src/main/resources/dsl/customerapplication.yml
src/test/resources/dsl/customerapplication.json
src/test/resources/dsl/customerapplication.yml

Updates DSL sample to add support for actions sleep before/after and sleep state (workflow.sleep)

Dsl Sample - add sleep before/after on actions and sleep state support

---

src/main/java/io/temporal/samples/fileprocessing/StoreActivitiesImpl.java
src/main/java/io/temporal/samples/hello/HelloException.java

Fixes to use Activity.wrap in activity code

Update workflow.wrap to activity.wrap

---

build.gradle

Upgrade to SDK v1.5.0

---

README.md
build.gradle
src/main/java/io/temporal/samples/metrics/MetricsStarter.java
src/main/java/io/temporal/samples/metrics/MetricsUtils.java
src/main/java/io/temporal/samples/metrics/MetricsWorker.java
src/main/java/io/temporal/samples/metrics/README.md
src/main/java/io/temporal/samples/metrics/activities/MetricsActivities.java
src/main/java/io/temporal/samples/metrics/activities/MetricsActivitiesImpl.java
src/main/java/io/temporal/samples/metrics/workflow/MetricsWorkflow.java
src/main/java/io/temporal/samples/metrics/workflow/MetricsWorkflowImpl.java

Adds sdk metrics sample which is similar to the Go sample: https://github.com/temporalio/samples-go/tree/main/metrics

sdk metrics sample

---

src/main/java/io/temporal/samples/hello/HelloPeriodic.java

The use of ContinueAsNew in the HelloPeriodic was not clear. This change aims to address that.

Improve the HelloPeriodic sample.

---

.gitignore
src/main/java/io/temporal/samples/hello/HelloPeriodic.java

- Added generated files to `.gitignore`. Not sure if they appeared while building or running or opening in VSCode, but thought it might be helpful to others if they were ignored.
- After `./gradlew build`, the formatting of `HelloPeriodic.java` changed. I'm guessing that should be included? Or if it's due to something odd in my environment, I can remove.

Add generated files to .gitignore

---

build.gradle
src/main/java/io/temporal/samples/dsl/DslActivitiesImpl.java
src/main/java/io/temporal/samples/dsl/DslWorkflowCache.java
src/main/java/io/temporal/samples/dsl/DynamicDslWorkflow.java
src/main/java/io/temporal/samples/dsl/README.md
src/main/java/io/temporal/samples/dsl/Starter.java
src/main/java/io/temporal/samples/dsl/model/ActResult.java
src/main/java/io/temporal/samples/dsl/model/Customer.java
src/main/java/io/temporal/samples/dsl/model/WorkflowData.java
src/main/java/io/temporal/samples/dsl/utils/DslWorkflowUtils.java
src/main/java/io/temporal/samples/dsl/utils/JQFilter.java
src/main/resources/dsl/customerapplication.json
src/main/resources/dsl/customerapplication.yml
src/main/resources/dsl/datainput.json
src/test/java/io/temporal/samples/dsl/DslWorkflowTest.java
src/test/resources/dsl/customerapplication.json
src/test/resources/dsl/customerapplication.yml
src/test/resources/dsl/datainput.json

updates dsl sample to:
1. add support for jq
2. add support for more dsl workflow states
3. allow activities to have custom object types rather than to use jsonnode
4. updated depends

update to dsl sample

---

build.gradle

upgrade to java sdk release 1.7.1

Upgrade to Java SDK 1.7.1

---

src/main/java/io/temporal/samples/metrics/MetricsStarter.java
src/main/java/io/temporal/samples/metrics/MetricsUtils.java
src/main/java/io/temporal/samples/metrics/MetricsWorker.java
src/main/java/io/temporal/samples/metrics/README.md
src/main/java/io/temporal/samples/metrics/activities/MetricsActivitiesImpl.java

* adds custom tags to show hows that can be added
* updates starter to not shut down so users can see all the metrics on both 8080/prometheus and 8081/prometheus

update metrics sample

---

README.md
src/main/java/io/temporal/samples/peractivityoptions/FailingActivities.java
src/main/java/io/temporal/samples/peractivityoptions/FailingActivitiesImpl.java
src/main/java/io/temporal/samples/peractivityoptions/PerActivityOptionsWorkflow.java
src/main/java/io/temporal/samples/peractivityoptions/PerActivityOptionsWorkflowImpl.java
src/main/java/io/temporal/samples/peractivityoptions/README.md
src/main/java/io/temporal/samples/peractivityoptions/Starter.java
src/test/java/io/temporal/samples/peractivityoptions/PerActivityOptionsTest.java

Adds sample to showcase use of WorkflowImplementationOptions->setActivityOptions

Add per-activity-type options sample

---

build.gradle

update to sdk verison 1.8.1

---

src/main/java/io/temporal/samples/hello/HelloDetachedCancellationScope.java

Sets heartbeat timeout to HelloDetachedCancellationScope sample

Add heartbeat timeout to sample

---

README.md
build.gradle
src/main/java/io/temporal/samples/payloadconverter/cloudevents/CEWorkflow.java
src/main/java/io/temporal/samples/payloadconverter/cloudevents/CEWorkflowImpl.java
src/main/java/io/temporal/samples/payloadconverter/cloudevents/CloudEventsPayloadConverter.java
src/main/java/io/temporal/samples/payloadconverter/cloudevents/README.md
src/main/java/io/temporal/samples/payloadconverter/cloudevents/Starter.java
src/main/java/io/temporal/samples/payloadconverter/crypto/CryptoWorkflow.java
src/main/java/io/temporal/samples/payloadconverter/crypto/CryptoWorkflowImpl.java
src/main/java/io/temporal/samples/payloadconverter/crypto/MyCustomer.java
src/main/java/io/temporal/samples/payloadconverter/crypto/README.md
src/main/java/io/temporal/samples/payloadconverter/crypto/Starter.java
src/test/java/io/temporal/samples/payloadconverter/CloudEventsPayloadConverterTest.java
src/test/java/io/temporal/samples/payloadconverter/CryptoPayloadConverterTest.java

Adds crypto data converter sample using https://github.com/codesqueak/jackson-json-crypto

Adding Crypto Data Converter Sample

---

.buildkite/pipeline.yml
README.md
docker/buildkite/Dockerfile
docker/buildkite/docker-compose.yaml

Removed references to FOSSA
FOSSA is being decommissioned.

Remove FOSSA references

---

build.gradle

removes snapshot repo and snapshot depends

remove snapshots

---

build.gradle

JavaSDK release 1.9.1

---

README.md

Just a small fix on the "Table of Contents"  section on the readme file. 
1. Closes 

readme-fix-table-of-content

---

src/main/java/io/temporal/samples/hello/HelloCancellationScope.java

Adapt HelloCancellationScope to change of activity heartbeating behavior implemented in 1.7.0: https://github.com/temporalio/sdk-java/issues/906

Fix heartbeating in HelloCancellationScope

---

src/main/java/io/temporal/samples/dsl/DslWorkflowCache.java
src/main/java/io/temporal/samples/dsl/DynamicDslWorkflow.java
src/main/java/io/temporal/samples/dsl/README.md
src/main/java/io/temporal/samples/dsl/Starter.java
src/main/java/io/temporal/samples/dsl/model/WorkflowData.java
src/main/resources/dsl/bankingtransactionssubflow/childworkflow.json
src/main/resources/dsl/bankingtransactionssubflow/datainput.json
src/main/resources/dsl/bankingtransactionssubflow/parentworkflow.json

Adds support to dsl sample for subflows/child workflows

DSL Sample support for child workflow invocations

---

build.gradle

Update SDK version to 1.14.0

---

README.md
src/main/java/io/temporal/samples/ssl/SslEnabledWorker.java

Update readme and SslEnabledWorker code

---

src/main/java/io/temporal/samples/asyncchild/Starter.java

Removed `CustomerActivitiesImpl` activity registration, which is not part of the workflows `ParentWorkflow`.
1. Closes 
I have tested it by running the "starter" class and by running the associated test, it is working as before. 

remove activity registration CustomerActivitiesImpl

---

build.gradle

Update SDK to 1.16.0

---

build.gradle

fix 1.16 opentracing module

---

src/main/java/io/temporal/samples/metrics/MetricsStarter.java
src/main/java/io/temporal/samples/metrics/MetricsWorker.java
src/test/java/io/temporal/samples/metrics/MetricsTest.java

Added test that verified custom metrics published by users 

---

src/test/java/io/temporal/samples/hello/HelloChildJUnit5Test.java

Added test to HelloChild with JUnit 5, related forum question https://community.temporal.io/t/mocking-child-workflows-in-java/5598/4
1. Closes 

add hello child test with junit 5

---

src/main/java/io/temporal/samples/interceptor/ClientCounter.java
src/main/java/io/temporal/samples/interceptor/InterceptorStarter.java
src/main/java/io/temporal/samples/interceptor/README.md
src/main/java/io/temporal/samples/interceptor/SimpleClientCallsInterceptor.java
src/main/java/io/temporal/samples/interceptor/SimpleClientInterceptor.java
src/main/java/io/temporal/samples/interceptor/SimpleCountActivityInboundCallsInterceptor.java
src/main/java/io/temporal/samples/interceptor/SimpleCountWorkflowInboundCallsInterceptor.java
src/main/java/io/temporal/samples/interceptor/WorkerCounter.java
src/test/java/io/temporal/samples/interceptor/ClientCountInterceptorTest.java
src/test/java/io/temporal/samples/interceptor/WorkerCountInterceptorTest.java

Added sample of client interceptor, implementation and test
Note that I have renamed some files and variables to make clear that there are two interceptors and two counters, for worker and client

added client interceptor

---

.github/CODEOWNERS

adding codeowner

---

src/main/java/io/temporal/samples/hello/HelloSearchAttributes.java

Fix reference to wf impl of another sample

small fix to hello search attributes sample

---

README.md
docker/buildkite/README.md
src/main/java/io/temporal/samples/asyncchild/README.md
src/main/java/io/temporal/samples/batch/heartbeatingactivity/README.md
src/main/java/io/temporal/samples/batch/iterator/README.md
src/main/java/io/temporal/samples/batch/slidingwindow/README.md
src/main/java/io/temporal/samples/bookingsaga/README.md
src/main/java/io/temporal/samples/dsl/README.md
src/main/java/io/temporal/samples/getresultsasync/README.md
src/main/java/io/temporal/samples/listworkflows/README.md
src/main/java/io/temporal/samples/moneybatch/README.md
src/main/java/io/temporal/samples/payloadconverter/crypto/README.md
src/main/java/io/temporal/samples/peractivityoptions/README.md
src/main/java/io/temporal/samples/polling/frequent/README.md
src/main/java/io/temporal/samples/polling/infrequent/README.md
src/main/java/io/temporal/samples/polling/periodicsequence/README.md
src/main/java/io/temporal/samples/terminateworkflow/README.md
src/main/java/io/temporal/samples/tracing/README.md

Links to other Temporal pages (within the repository and for docs.tempora.io) were updated to reflect ongoing changes to these areas.
Capitalization mistakes regarding Temporal terms were also fixed.
These links need to get the user to the right place.
Any docs linking to the samples repo will be checked.

Tw 219 update links samples java

---

README.md

Links to other documents within this repository were shortened.
It's a lot easier to parse.

shortened links, updated legacy

---

src/main/java/io/temporal/samples/polling/frequent/README.md
src/main/java/io/temporal/samples/polling/infrequent/InfrequentPollingWorkflowImpl.java
src/main/java/io/temporal/samples/polling/infrequent/README.md
src/main/java/io/temporal/samples/polling/periodicsequence/PeriodicPollingStarter.java
src/main/java/io/temporal/samples/polling/periodicsequence/README.md

As a part of https://github.com/temporalio/samples-go/issues/239 I found this :)

Fixing README

---

src/main/java/io/temporal/samples/polling/periodicsequence/PeriodicPollingChildWorkflowImpl.java

Updates activity options for periodic polling sample (PeriodicPollingChildWorkflow)

Update activity options for PeriodicPollingChildWorkflow sample

---

src/main/java/io/temporal/samples/batch/slidingwindow/README.md

fix class name

---

src/main/java/io/temporal/samples/hello/HelloSearchAttributes.java
src/test/java/io/temporal/samples/hello/HelloSearchAttributesTest.java

add test to HelloSearchAttributes

---

README.md
src/main/java/io/temporal/samples/encodefailures/CustomerAgeCheck.java
src/main/java/io/temporal/samples/encodefailures/CustomerAgeCheckImpl.java
src/main/java/io/temporal/samples/encodefailures/InvalidCustomerException.java
src/main/java/io/temporal/samples/encodefailures/MyCustomer.java
src/main/java/io/temporal/samples/encodefailures/README.md
src/main/java/io/temporal/samples/encodefailures/SimplePrefixPayloadCodec.java
src/main/java/io/temporal/samples/encodefailures/Starter.java
src/test/java/io/temporal/samples/encodefailures/EncodeFailuresTest.java

Sample that shows how to set up simple payload codec to encode/decode failure messages

Sample - simple payload coded use to encode/decode failure messages

---

core/src/main/java/io/temporal/samples/dsl/README.md

Fix links in DSL sample

---

README.md
core/src/main/java/io/temporal/samples/hello/HelloSchedules.java
core/src/main/java/io/temporal/samples/hello/README.md

Add sample showing schedules API based on the Go sample
Show users how to use the new schedules API

Add sample showing schedules API

---

core/src/main/java/io/temporal/samples/ssl/MyWorkflow.java
core/src/main/java/io/temporal/samples/ssl/MyWorkflowImpl.java
core/src/main/java/io/temporal/samples/ssl/README.md
core/src/main/java/io/temporal/samples/ssl/Starter.java
core/src/main/java/io/temporal/samples/terminateworkflow/README.md

Added readme and the missing code to start a workflow execution.
I think it will be handy for users to have a full example, not only the worker configuration. 
1. Closes 
closes #463

added ssl full example and readme

---

build.gradle

Update Java SDK to v1.20.0

---

.github/CODEOWNERS

add sdk team as codeowner

---

README.md
build.gradle
core/build.gradle
core/src/main/java/io/temporal/samples/hello/HelloActivity.java
core/src/main/java/io/temporal/samples/hello/HelloActivityExclusiveChoice.java
core/src/main/java/io/temporal/samples/hello/HelloActivityRetry.java
core/src/main/java/io/temporal/samples/hello/HelloAsync.java
core/src/main/java/io/temporal/samples/hello/HelloAsyncActivityCompletion.java
core/src/main/java/io/temporal/samples/hello/HelloAsyncLambda.java
core/src/main/java/io/temporal/samples/hello/HelloDetachedCancellationScope.java
core/src/main/java/io/temporal/samples/hello/HelloDynamic.java
core/src/main/java/io/temporal/samples/hello/HelloException.java
core/src/main/java/io/temporal/samples/hello/HelloParallelActivity.java
core/src/main/java/io/temporal/samples/hello/HelloSaga.java
core/src/main/java/io/temporal/samples/hello/HelloSearchAttributes.java
core/src/main/java/io/temporal/samples/hello/HelloSideEffect.java
core/src/main/java/io/temporal/samples/polling/frequent/FrequentPollingWorkflowImpl.java
core/src/main/java/io/temporal/samples/polling/infrequent/InfrequentPollingWorkflowImpl.java
core/src/main/java/io/temporal/samples/ssl/Starter.java
core/src/test/java/io/temporal/samples/hello/HelloDynamicTest.java
springboot/src/main/java/io/temporal/samples/springboot/SamplesController.java
springboot/src/main/java/io/temporal/samples/springboot/kafka/KafkaActivityImpl.java
springboot/src/main/java/io/temporal/samples/springboot/kafka/MessageController.java

fixes all errorprone and compiler warnings
fixes main readme

Fix errorprone and compiler warnings

---

README.md
springboot/src/main/java/io/temporal/samples/springboot/SamplesController.java
springboot/src/main/java/io/temporal/samples/springboot/customize/CustomizeActivity.java
springboot/src/main/java/io/temporal/samples/springboot/customize/CustomizeActivityImpl.java
springboot/src/main/java/io/temporal/samples/springboot/customize/CustomizeWorkflow.java
springboot/src/main/java/io/temporal/samples/springboot/customize/CustomizeWorkflowImpl.java
springboot/src/main/java/io/temporal/samples/springboot/customize/README.md
springboot/src/main/java/io/temporal/samples/springboot/customize/TemporalOptionsConfig.java
springboot/src/main/resources/templates/customize.html
springboot/src/main/resources/templates/index.html
springboot/src/test/java/io/temporal/samples/springboot/CustomizeSampleTest.java

Sample that shows how to configure custom options.
Sample shows also how to configure worker options for specific worker/task queue.

SpringBoot Sample - customize options

---

build.gradle

Update Java SDK 1.20.1

---

README.md
springboot/src/main/resources/application-tc.yaml
springboot/src/main/resources/application.yaml

This pr adds the needed configuration to run the SpringBoot samples connecting to Temporal Cloud
1. Closes 

add config to run spring boot samples connecting to Temporal Cloud

---

build.gradle

Update SDK to v1.21.0

---

build.gradle

Update Java SDK 1.21.1

---

core/src/test/java/io/temporal/samples/hello/HelloChildJUnit5Test.java

small fix for junit5 child test

fix for child mock test

---

build.gradle
core/src/test/java/io/temporal/samples/tracing/TracingTest.java
springboot/src/main/java/io/temporal/samples/springboot/TemporalSpringbootSamplesApplication.java

Update Java SDK to v1.22.0

---

README.md
core/src/main/java/io/temporal/samples/hello/HelloAwait.java
core/src/test/java/io/temporal/samples/hello/HelloAwaitTest.java

New sample to demonstrate `Workflow.await`. It also shows how to test the `await` timeout by using `testEnvironment.sleep`.

Added HelloAwait sample

---

core/src/main/java/io/temporal/samples/dsl/README.md

update dsl sample readme

---

.gitignore
README.md
settings.gradle
springboot-basic/build.gradle
springboot-basic/src/main/java/io/temporal/samples/springboot/SamplesController.java
springboot-basic/src/main/java/io/temporal/samples/springboot/TemporalSpringbootSamplesApplication.java
springboot-basic/src/main/java/io/temporal/samples/springboot/hello/HelloActivity.java
springboot-basic/src/main/java/io/temporal/samples/springboot/hello/HelloActivityImpl.java
springboot-basic/src/main/java/io/temporal/samples/springboot/hello/HelloWorkflow.java
springboot-basic/src/main/java/io/temporal/samples/springboot/hello/HelloWorkflowImpl.java
springboot-basic/src/main/java/io/temporal/samples/springboot/hello/README.md
springboot-basic/src/main/java/io/temporal/samples/springboot/hello/model/Person.java
springboot-basic/src/main/resources/application-tc.yaml
springboot-basic/src/main/resources/application.yaml
springboot-basic/src/main/resources/static/js/jquery.sse.js
springboot-basic/src/main/resources/static/js/samplessse.js
springboot-basic/src/main/resources/templates/fragments.html
springboot-basic/src/main/resources/templates/hello.html
springboot-basic/src/main/resources/templates/index.html
springboot-basic/src/test/java/io/temporal/samples/springboot/HelloSampleTest.java
springboot-basic/src/test/resources/application.yaml
springboot/src/main/java/io/temporal/samples/springboot/customize/README.md
springboot/src/main/java/io/temporal/samples/springboot/kafka/README.md
springboot/src/main/java/io/temporal/samples/springboot/metrics/README.md
springboot/src/main/java/io/temporal/samples/springboot/update/README.md

Add basic springboot sample with minimal dependencies just showcasing Temporal + Springboot

Add basic SpringBoot sample

---

README.md
core/src/main/java/io/temporal/samples/hello/HelloSignalWithTimer.java
core/src/main/java/io/temporal/samples/hello/README.md
core/src/test/java/io/temporal/samples/hello/HelloSignalWithTimerTest.java

Sample that shows how to wait for signals for some duration of time and then process last one received
and continueasnew. exit signal cancels timer and completes execution chain

Timer based signal processing sample

---

build.gradle

Update Java SDK to v1.23.0

---

build.gradle

Update Java SDK to v1.23.2

---

springboot/src/main/java/io/temporal/samples/springboot/camel/CamelRoutes.java
springboot/src/main/java/io/temporal/samples/springboot/camel/OrderActivityImpl.java
springboot/src/main/java/io/temporal/samples/springboot/camel/README.md

update to camel sample to call route from activity

update springboot camel sample

---

build.gradle
springboot-basic/build.gradle
springboot-basic/src/main/resources/application-tc.yaml
springboot/build.gradle
springboot/src/main/resources/application-tc.yaml

Update Java SDK

---

core/src/main/java/io/temporal/samples/ssl/README.md
core/src/main/java/io/temporal/samples/ssl/Starter.java

Add details to the mTLS sample showing how to refresh mTLS credentials.

Add details showing how to refresh mTLS

---

springboot/src/test/java/io/temporal/samples/springboot/HelloSampleTestMockedActivity.java

adds springboot test to show how to mock activity

SpringBoot test with mocked activity

---

README.md
springboot/src/main/java/io/temporal/samples/springboot/SamplesController.java
springboot/src/main/java/io/temporal/samples/springboot/actuator/README.md
springboot/src/main/java/io/temporal/samples/springboot/actuator/WorkerActuatorEndpoint.java
springboot/src/main/resources/application.yaml
springboot/src/main/resources/templates/actuator.html
springboot/src/main/resources/templates/index.html

custom actuator springboot sample - shows worker info

spring boot custom actuator worker endpoint sample

---

build.gradle

Update Java SDK to v1.24.1

---

core/src/main/java/io/temporal/samples/metrics/MetricsStarter.java
core/src/main/java/io/temporal/samples/metrics/MetricsWorker.java

Fixed URL for Prometheus metrics endpoint in sysout.
The URL was incorrect, leading to issues in accessing Prometheus metrics.
Fixed the URL in sysout.
Verified functionality with correct URL.
Tested by running the application and verifying that the Prometheus metrics endpoint is accessible via the updated URL.
Any docs updates needed?
No documentation updates needed.

fixing url for prometheus metrics endpoint in sysout

---

README.md
core/src/main/java/io/temporal/samples/bookingsaga/Booking.java
core/src/main/java/io/temporal/samples/bookingsaga/README.md
core/src/main/java/io/temporal/samples/bookingsaga/TripBookingActivities.java
core/src/main/java/io/temporal/samples/bookingsaga/TripBookingActivitiesImpl.java
core/src/main/java/io/temporal/samples/bookingsaga/TripBookingClient.java
core/src/main/java/io/temporal/samples/bookingsaga/TripBookingWorker.java
core/src/main/java/io/temporal/samples/bookingsaga/TripBookingWorkflow.java
core/src/main/java/io/temporal/samples/bookingsaga/TripBookingWorkflowImpl.java
core/src/main/java/io/temporal/samples/bookingsyncsaga/Booking.java
core/src/main/java/io/temporal/samples/bookingsyncsaga/README.md
core/src/main/java/io/temporal/samples/bookingsyncsaga/TripBookingActivities.java
core/src/main/java/io/temporal/samples/bookingsyncsaga/TripBookingActivitiesImpl.java
core/src/main/java/io/temporal/samples/bookingsyncsaga/TripBookingClient.java
core/src/main/java/io/temporal/samples/bookingsyncsaga/TripBookingWorker.java
core/src/main/java/io/temporal/samples/bookingsyncsaga/TripBookingWorkflow.java
core/src/main/java/io/temporal/samples/bookingsyncsaga/TripBookingWorkflowImpl.java
core/src/test/java/io/temporal/samples/bookingsaga/TripBookingWorkflowJUnit5Test.java
core/src/test/java/io/temporal/samples/bookingsaga/TripBookingWorkflowTest.java
core/src/test/java/io/temporal/samples/bookingsyncsaga/TripBookingWorkflowTest.java

Changed SAGA sample to add compensations before the action.
Wrapped call to compensate in a detached cancellation scope. 
Added synchronous SAGA sample demonstrating how to unblock the caller and execute compensations in the background.

Refactored SAGA sample and added Synchronous SAGA sample.

---

core/src/main/java/io/temporal/samples/bookingsaga/TripBookingWorker.java
core/src/main/java/io/temporal/samples/bookingsyncsaga/TripBookingWorker.java

Fix SAGA samples broken by https://github.com/temporalio/samples-java/pull/647.

Fix SAGA samples

---

build.gradle

Bump Java SDK to v1.26.1

---

core/src/main/java/io/temporal/samples/safemessagepassing/ClusterManagerWorkflow.java

Fix formatting check https://github.com/temporalio/samples-java/actions/runs/11668460249/job/32488165277

Fix formatting

---

build.gradle
core/src/main/java/io/temporal/samples/nexus/options/ClientOptions.java

Update to Java SDK v1.28.1

---

core/src/main/java/io/temporal/samples/nexus/handler/NexusServiceImpl.java
core/src/main/java/io/temporal/samples/nexuscontextpropagation/handler/NexusServiceImpl.java

Call out `WorkflowRunOperation.fromWorkflowHandler` since some users didn't realize this API was an option

Call out WorkflowRunOperation.fromWorkflowHandler

---

build.gradle

Update Java SDK to v1.31.0
