temporalio/samples-java

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Task :checkDependencyUpdates
New dependency version: com.google.errorprone:error_prone_core: 2.4.0 -> 2.6.0
New dependency version: commons-configuration:commons-configuration: 1.10 -> 20041012.002804
New dependency version: junit:junit: 4.13.1 -> 4.13.2
New dependency version: name.remal.check-updates:name.remal.check-updates.gradle.plugin: 1.1.4 -> 1.3.1
New dependency version: net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin: 1.3.0 -> 2.0.1
> Task :checkGradleUpdates
New Gradle version is available: 7.0 (downloadUrl: https://services.gradle.org/distributions/gradle-7.0-bin.zip)
> Gradle & Dependencies Update

- build.gradle
- src/main/java/io/temporal/samples/hello/HelloActivity.java
- src/main/java/io/temporal/samples/hello/HelloLocalActivity.java
- src/test/java/io/temporal/samples/bookingsaga/TripBookingWorkflowTest.java
- src/test/java/io/temporal/samples/fileprocessing/FileProcessingTest.java
- src/test/java/io/temporal/samples/hello/HelloActivityRetryTest.java
- src/test/java/io/temporal/samples/hello/HelloActivityTest.java
- src/test/java/io/temporal/samples/hello/HelloAsyncLambdaTest.java
- src/test/java/io/temporal/samples/hello/HelloChildTest.java
- src/test/java/io/temporal/samples/hello/HelloCronTest.java
- src/test/java/io/temporal/samples/hello/HelloExceptionTest.java
- src/test/java/io/temporal/samples/hello/HelloLocalActivityTest.java
- src/test/java/io/temporal/samples/hello/HelloPeriodicTest.java
- src/test/java/io/temporal/samples/moneybatch/TransferWorkflowTest.java
- src/test/java/io/temporal/samples/moneytransfer/TransferWorkflowTest.java
Update test code to Mockito 3 and adapt when needed. This PR is inspired by https://github.com/temporalio/sdk-java/issues/332 and should provide an example of how a recent Mockito can be used with Temporal SDK.
* Upgrade Mockito and PowerMock to the latest versions
* Fix deprecation warnings
* Use `withSettings().withoutAnnotations()` in `HelloActivityTest` to prevent Mockito from copying annotations from activity interface to mock class
* Re-enable `HelloChildTest.testMockedChild()` and `HelloExceptionTest.testChildWorkflowTimeout()` as they no longer fail with Mockito 3, presumably due to Mockito's switch to ByteBuddy
> Upgrade Mockito to 3.x

- README.md
This PR fixes the link to Java docs in main readme
> Fix for Readme link to Java docs

- README.md
README.md was updated to include instructions to run samples when docker is not running on `localhost`.
Because the information contained in README.md does not apply to a commonly used docker daemon setup.
1. Closes 
> Add instructions to run samples when Docker is not running on localhost

- src/main/java/io/temporal/samples/updatabletimer/README.md
- src/main/java/io/temporal/samples/updatabletimer/UpdatableTimer.java
Small tweak in the _Updatable Timer_ sample to avoid calling a non-deterministic local time zone API form the workflow.
> Remove non-deterministic call in the UpdatableTimer sample.

- build.gradle
adds the execute task back to build.gradle (was mistakenly removed during previous cleanup)
> Add execute task back

- src/main/java/io/temporal/samples/hello/HelloCancellationScope.java
replaces call to setActivityPollThreadCount with setMaxConcurrentActivityTaskPollers
> Fix call to deprecated setActivityPollThreadCount

- src/main/java/io/temporal/samples/hello/HelloSearchAttributes.java
fixes use of deprecated api in search attributes samples:
> Task :compileJava
Note: /samples-java/src/main/java/io/temporal/samples/hello/HelloSearchAttributes.java uses or overrides a deprecated API.
> fix use of deprecated api

- README.md
- build.gradle
- docker/buildkite/Dockerfile
- src/main/java/io/temporal/samples/batch/iterator/IteratorBatchWorkflowImpl.java
- src/main/java/io/temporal/samples/batch/iterator/RecordLoader.java
- src/main/java/io/temporal/samples/batch/iterator/RecordLoaderImpl.java
- src/main/java/io/temporal/samples/batch/iterator/RecordProcessorWorkflow.java
- src/main/java/io/temporal/samples/batch/iterator/RecordProcessorWorkflowImpl.java
- src/main/java/io/temporal/samples/batch/iterator/SingleRecord.java
- src/main/java/io/temporal/samples/batch/slidingwindow/SlidingWindowBatchWorkflowImpl.java
- src/test/java/io/temporal/samples/batch/iterator/IteratorIteratorBatchWorkflowTest.java
Build fails right now on Java 17 with unexpected (and incorrect):
```
Detected Java syntax errors in the following files (you can exclude them from this task, see "https://github.com/sherter/google-java-format-gradle-plugin" for details):
```
Migrating to spotless from not supported anymore `com.github.sherter.google-java-format` plugin.
Disable code style check on java <11 as the latest google java format versions require Java 11.
> Fix build under the latest JDKs by migrating on the spotless plugin

- src/main/java/io/temporal/samples/polling/frequent/FrequentPollingWorkflowImpl.java
From this discussion https://github.com/temporalio/samples-go/pull/246/files#r1071564133 it appears that 10 seconds is an insufficient timeout for the example
> Backporting requirement for higher start to close timeout from #239

- src/main/java/io/temporal/samples/polling/frequent/FrequentPollingActivityImpl.java
This pr addresses the optionality of the heartbeat message, as suggested in https://github.com/temporalio/samples-go/pull/246#discussion_r1071570274
It the payload is optional, it might be in the future that the workflow engine persistence layer skip a write to the database
> Empty payload for heartbeating in frequent polling activities

- README.md
- build.gradle
- springboot/build.gradle
- springboot/src/main/java/io/temporal/samples/springboot/SamplesController.java
- springboot/src/main/java/io/temporal/samples/springboot/hello/HelloActivity.java
- springboot/src/main/java/io/temporal/samples/springboot/hello/HelloActivityImpl.java
- springboot/src/main/java/io/temporal/samples/springboot/hello/HelloWorkflow.java
- springboot/src/main/java/io/temporal/samples/springboot/hello/README.md
- springboot/src/main/java/io/temporal/samples/springboot/hello/model/Person.java
- springboot/src/main/resources/templates/hello.html
- springboot/src/main/resources/templates/index.html
- springboot/src/test/java/io/temporal/samples/springboot/HelloSampleTest.java
Adding 'ui' (html pages) for spring boot samples (ok just one sample but adding more :) )
Users can now just start spring boot:
./gradlew bootRun
and then go to localhost:3030 to see page with all samples and then click on each sample to get to page for that sample.
for example for "hello" one:
Sample form:
After entering values and running wf:
> adding 'ui' to springboot samples

- README.md
- springboot/build.gradle
- springboot/src/main/java/io/temporal/samples/springboot/SamplesController.java
- springboot/src/main/java/io/temporal/samples/springboot/metrics/README.md
- springboot/src/main/resources/application.yaml
- springboot/src/main/resources/templates/index.html
- springboot/src/main/resources/templates/metrics.html
This shows users how easy it is to set up sdk metrics with spring boot and actuator.
There is no code for this sample. Just update to application.yaml to set up actuator endpoint
and page that shows users how to do this and also link to endpoint where they can see their metrics (this is set up when 
you start spring boot in samples already so nothing to do really)
/metrics endpoint:
> spring boot samples - sdk metrics

- README.md
- springboot/build.gradle
- springboot/src/main/java/io/temporal/samples/springboot/SamplesController.java
- springboot/src/main/java/io/temporal/samples/springboot/update/ProductNotAvailableForAmountException.java
- springboot/src/main/java/io/temporal/samples/springboot/update/PurchaseActivities.java
- springboot/src/main/java/io/temporal/samples/springboot/update/PurchaseActivitiesImpl.java
- springboot/src/main/java/io/temporal/samples/springboot/update/PurchaseWorkflow.java
- springboot/src/main/java/io/temporal/samples/springboot/update/PurchaseWorkflowImpl.java
- springboot/src/main/java/io/temporal/samples/springboot/update/README.md
- springboot/src/main/java/io/temporal/samples/springboot/update/ResourceNotFoundException.java
- springboot/src/main/java/io/temporal/samples/springboot/update/model/Product.java
- springboot/src/main/java/io/temporal/samples/springboot/update/model/ProductRepository.java
- springboot/src/main/java/io/temporal/samples/springboot/update/model/Purchase.java
- springboot/src/main/resources/application.yaml
- springboot/src/main/resources/data.sql
- springboot/src/main/resources/templates/fragments.html
- springboot/src/main/resources/templates/hello.html
- springboot/src/main/resources/templates/index.html
- springboot/src/main/resources/templates/metrics.html
- springboot/src/main/resources/templates/update.html
- springboot/src/test/java/io/temporal/samples/springboot/HelloUpdateTest.java
- springboot/src/test/resources/application.yaml
- springboot/src/test/resources/data.sql
Sync Update SpringBoot Sample
This sample shows how to use update feature. Uses jpa and h2 in-memory db for the inventory. 
User can enter a fishing item to purchase from inventory and define the amount.
The update validator checks if inventory has item and the amount (local activity)
The update then updates the db (local activity).
If amount you wan to purchase is > than whats in inventory the validator fails and shows message.
On success purchase the inventory table is updated dynamically..
(this pr also includes small changes to other sample html pages, like using fragments for header and footer)
> SpringBoot - Sync Update Example

- build.gradle
- springboot/build.gradle
- springboot/src/main/java/io/temporal/samples/springboot/SamplesController.java
- springboot/src/main/java/io/temporal/samples/springboot/kafka/KafkaActivity.java
- springboot/src/main/java/io/temporal/samples/springboot/kafka/KafkaActivityImpl.java
- springboot/src/main/java/io/temporal/samples/springboot/kafka/KafkaConfig.java
- springboot/src/main/java/io/temporal/samples/springboot/kafka/MessageController.java
- springboot/src/main/java/io/temporal/samples/springboot/kafka/MessageWorkflow.java
- springboot/src/main/java/io/temporal/samples/springboot/kafka/MessageWorkflowImpl.java
- springboot/src/main/java/io/temporal/samples/springboot/kafka/README.md
- springboot/src/main/resources/application.yaml
- springboot/src/main/resources/static/js/jquery.sse.js
- springboot/src/main/resources/static/js/samplessse.js
- springboot/src/main/resources/templates/index.html
- springboot/src/main/resources/templates/kafka.html
- springboot/src/test/java/io/temporal/samples/springboot/HelloSampleTest.java
- springboot/src/test/java/io/temporal/samples/springboot/KafkaConsumerTestHelper.java
- springboot/src/test/java/io/temporal/samples/springboot/KafkaSampleTest.java
- springboot/src/test/java/io/temporal/samples/springboot/UpdateSampleTest.java
- springboot/src/test/resources/application.yaml
This sample shows use case where you have existing systems in place that deal with a different queueing tech like Kafka.
In this case you might want to start wf exec when a message is placed on kafka topic and have the kafka consumer trigger
workflow execution. The workflow during its execution can send messages to kafka which can be consumed by some other pretend-existing systems.
It use embedded kafka so users don't have to download and manually start zookeper and kafka. 
For the sample html page user enters a message into form, submitting form sends event to kafka topic.
Kafka consumer then starts wf execution. Activities publish messages to kafka topic.
These messages are then pushed to ui via server side events and are dynamically presented on page.
> SpringBoot - Kafka Sample

- README.md
- build.gradle
- gradle.properties
- springboot/build.gradle
allows support for both springboot 2 and 3 for the samples. springboot 2 is still default but can change to 3 via gradle.properties
> update to SpringBoot 3

- README.md
- core/src/main/java/io/temporal/samples/hello/HelloDelayedStart.java
- core/src/test/java/io/temporal/samples/hello/HelloDelayedStartTest.java
- springboot/build.gradle
Simple hello sample that shows delayed start api
> Hello delayed start sample

- README.md
- core/src/main/java/io/temporal/samples/hello/HelloCancellationScopeWithTimer.java
- core/src/test/java/io/temporal/samples/hello/HelloCancellationScopeWithTimerTest.java
adds sample that cancels activity and completes exec on workflow timer firing
this can be linked to when we tell users not to use workflow run/execution timeout which is not recommended
> add cancelation sample with workflow timer

- README.md
- build.gradle
- springboot/build.gradle
- springboot/src/main/java/io/temporal/samples/springboot/SamplesController.java
- springboot/src/main/java/io/temporal/samples/springboot/camel/CamelConfig.java
- springboot/src/main/java/io/temporal/samples/springboot/camel/CamelResource.java
- springboot/src/main/java/io/temporal/samples/springboot/camel/CamelRoutes.java
- springboot/src/main/java/io/temporal/samples/springboot/camel/OfficeOrder.java
- springboot/src/main/java/io/temporal/samples/springboot/camel/OrderActivity.java
- springboot/src/main/java/io/temporal/samples/springboot/camel/OrderActivityImpl.java
- springboot/src/main/java/io/temporal/samples/springboot/camel/OrderRepository.java
- springboot/src/main/java/io/temporal/samples/springboot/camel/OrderWorkflow.java
- springboot/src/main/java/io/temporal/samples/springboot/camel/OrderWorkflowImpl.java
- springboot/src/main/java/io/temporal/samples/springboot/camel/README.md
- springboot/src/main/resources/data.sql
- springboot/src/main/resources/templates/camel.html
- springboot/src/main/resources/templates/index.html
- springboot/src/test/java/io/temporal/samples/springboot/CamelSampleTest.java
This sample shows possible integration of Temporal in Apache Camel application. 
Shows how to define a Camel Route and start a Workflow from it to gain advantage of Temporal.
> SpringBoot - Apache Camel Sample

- core/src/main/java/io/temporal/samples/hello/HelloTypedSearchAttributes.java
Just adding KeywordList type to typed SA sample. Was a recent question about this in slack
> Add KeyWordList type to typed SA sample

- README.md
- core/src/main/java/io/temporal/samples/excludefrominterceptor/README.md
- core/src/main/java/io/temporal/samples/excludefrominterceptor/RunMyWorkflows.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/activities/ForInterceptorActivities.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/activities/ForInterceptorActivitiesImpl.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/activities/MyActivities.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/activities/MyActivitiesImpl.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/interceptor/MyActivityInboundCallsInterceptor.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/interceptor/MyWorkerInterceptor.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/interceptor/MyWorkflowInboundCallsInterceptor.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/interceptor/MyWorkflowOutboundCallsInterceptor.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/workflows/MyWorkflow.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/workflows/MyWorkflowOne.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/workflows/MyWorkflowOneImpl.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/workflows/MyWorkflowTwo.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/workflows/MyWorkflowTwoImpl.java
- core/src/test/java/io/temporal/samples/excludefrominterceptor/ExcludeFromInterceptorTest.java
Sample that shows how can exclude certain workflow and activity types currently from interceptors
> Sample - exclude workflow/activity types from interceptors

- build.gradle
- core/build.gradle
- core/src/main/java/io/temporal/samples/nexus/README.MD
- core/src/main/java/io/temporal/samples/nexus/caller/CallerStarter.java
- core/src/main/java/io/temporal/samples/nexus/caller/CallerWorker.java
- core/src/main/java/io/temporal/samples/nexus/caller/EchoCallerWorkflow.java
- core/src/main/java/io/temporal/samples/nexus/caller/EchoCallerWorkflowImpl.java
- core/src/main/java/io/temporal/samples/nexus/caller/HelloCallerWorkflow.java
- core/src/main/java/io/temporal/samples/nexus/caller/HelloCallerWorkflowImpl.java
- core/src/main/java/io/temporal/samples/nexus/handler/HandlerWorker.java
- core/src/main/java/io/temporal/samples/nexus/handler/HelloHandlerWorkflow.java
- core/src/main/java/io/temporal/samples/nexus/handler/HelloHandlerWorkflowImpl.java
- core/src/main/java/io/temporal/samples/nexus/handler/NexusServiceImpl.java
- core/src/main/java/io/temporal/samples/nexus/options/ClientOptions.java
- core/src/main/java/io/temporal/samples/nexus/service/NexusService.java
- core/src/main/java/io/temporal/samples/nexus/service/description.md
- core/src/test/java/io/temporal/samples/nexus/caller/CallerWorkflowTest.java
Add Nexus sample based on the Go SDK sample https://github.com/temporalio/samples-go/tree/main/nexus
> Add Nexus sample

- core/src/main/java/io/temporal/samples/nexus/README.MD
- core/src/main/java/io/temporal/samples/nexus/options/ClientOptions.java
- core/src/main/java/io/temporal/samples/nexus/service/description.md
Fix nexus sample TLS settings to be the same as other TLS samples and update the `service.md`
> Fix nexus sample TLS settings

- core/src/main/java/io/temporal/samples/nexus/options/ClientOptions.java
Add API key auth option to Nexus sample
> Add API key option to Nexus sample

- README.md
- core/src/main/java/io/temporal/samples/safemessagepassing/ClusterManagerActivities.java
- core/src/main/java/io/temporal/samples/safemessagepassing/ClusterManagerActivitiesImpl.java
- core/src/main/java/io/temporal/samples/safemessagepassing/ClusterManagerWorkflow.java
- core/src/main/java/io/temporal/samples/safemessagepassing/ClusterManagerWorkflowImpl.java
- core/src/main/java/io/temporal/samples/safemessagepassing/ClusterManagerWorkflowStarter.java
- core/src/main/java/io/temporal/samples/safemessagepassing/ClusterManagerWorkflowWorker.java
- core/src/main/java/io/temporal/samples/safemessagepassing/README.md
- core/src/test/java/io/temporal/samples/safemessagepassing/ClusterManagerWorkflowWorkerTest.java
Add safe message passing sample. 
Code based on https://github.com/temporalio/samples-python/tree/main/message_passing/safe_message_handlers
> safe message passing sample

- README.md
- core/build.gradle
- core/src/main/java/io/temporal/samples/hello/HelloActivity.java
- core/src/main/java/io/temporal/samples/keymanagementencryption/awsencryptionsdk/EncryptedPayloads.java
- core/src/main/java/io/temporal/samples/keymanagementencryption/awsencryptionsdk/KeyringCodec.java
- core/src/main/java/io/temporal/samples/keymanagementencryption/awsencryptionsdk/README.md
Add sample showing how a user could use the AWS encryption SDK to encrypt payloads with AWS KMS
> Add sample showing AWS encryption SDK

- build.gradle
- core/src/main/java/io/temporal/samples/countinterceptor/SimpleCountWorkerInterceptor.java
- core/src/main/java/io/temporal/samples/earlyreturn/EarlyReturnClient.java
- core/src/main/java/io/temporal/samples/excludefrominterceptor/interceptor/MyWorkerInterceptor.java
- core/src/main/java/io/temporal/samples/retryonsignalinterceptor/RetryOnSignalWorkerInterceptor.java
- core/src/test/java/io/temporal/samples/earlyreturn/TransactionWorkflowTest.java
- core/src/test/java/io/temporal/samples/safemessagepassing/ClusterManagerWorkflowWorkerTest.java
Updated Java SDK to pull in new Update-with-Start API.
> Update Java SDK

- README.md
- core/src/main/java/io/temporal/samples/hello/HelloWorkflowTimer.java
- core/src/test/java/io/temporal/samples/hello/HelloWorkflowTimerTest.java
sample that shows use of workflow timer instead of using workflow run/exec timeouts
> Workflow timer sample

- core/src/main/java/io/temporal/samples/sleepfordays/README.md
- core/src/main/java/io/temporal/samples/sleepfordays/SendEmailActivity.java
- core/src/main/java/io/temporal/samples/sleepfordays/SendEmailActivityImpl.java
- core/src/main/java/io/temporal/samples/sleepfordays/SleepForDaysImpl.java
- core/src/main/java/io/temporal/samples/sleepfordays/SleepForDaysWorkflow.java
- core/src/main/java/io/temporal/samples/sleepfordays/Starter.java
- core/src/main/java/io/temporal/samples/sleepfordays/Worker.java
- core/src/test/java/io/temporal/samples/sleepfordays/SleepForDaysTest.java
> Add sleepfordays sample

- build.gradle
- core/src/main/java/io/temporal/samples/nexus/README.MD
- core/src/main/java/io/temporal/samples/nexus/caller/CallerStarter.java
- core/src/main/java/io/temporal/samples/nexus/caller/HelloCallerWorkflowImpl.java
- core/src/main/java/io/temporal/samples/nexus/handler/NexusServiceImpl.java
Update Nexus sample for v1.28.0
> Update Nexus sample for v1.28.0

- core/src/main/java/io/temporal/samples/nexus/README.MD
> Fix typo in nexus readme

- core/src/main/java/io/temporal/samples/nexus/handler/NexusServiceImpl.java
- core/src/main/java/io/temporal/samples/nexuscancellation/README.MD
- core/src/main/java/io/temporal/samples/nexuscancellation/caller/CallerStarter.java
- core/src/main/java/io/temporal/samples/nexuscancellation/caller/CallerWorker.java
- core/src/main/java/io/temporal/samples/nexuscancellation/caller/HelloCallerWorkflow.java
- core/src/main/java/io/temporal/samples/nexuscancellation/caller/HelloCallerWorkflowImpl.java
- core/src/main/java/io/temporal/samples/nexuscancellation/handler/HandlerWorker.java
- core/src/main/java/io/temporal/samples/nexuscancellation/handler/HelloHandlerWorkflowImpl.java
> Add Nexus cancellation sample

- core/src/test/java/io/temporal/samples/sleepfordays/SleepForDaysJUnit5Test.java
Added an example for SleepForDays workflow with JUnit5
There were no example yet
> test: added a junit 5 test on SleepForDays

- README.md
- core/src/main/java/io/temporal/samples/nexusmultipleargs/README.MD
- core/src/main/java/io/temporal/samples/nexusmultipleargs/caller/CallerStarter.java
- core/src/main/java/io/temporal/samples/nexusmultipleargs/caller/CallerWorker.java
- core/src/main/java/io/temporal/samples/nexusmultipleargs/caller/EchoCallerWorkflow.java
- core/src/main/java/io/temporal/samples/nexusmultipleargs/caller/EchoCallerWorkflowImpl.java
- core/src/main/java/io/temporal/samples/nexusmultipleargs/caller/HelloCallerWorkflow.java
- core/src/main/java/io/temporal/samples/nexusmultipleargs/caller/HelloCallerWorkflowImpl.java
- core/src/main/java/io/temporal/samples/nexusmultipleargs/handler/HandlerWorker.java
- core/src/main/java/io/temporal/samples/nexusmultipleargs/handler/HelloHandlerWorkflow.java
- core/src/main/java/io/temporal/samples/nexusmultipleargs/handler/HelloHandlerWorkflowImpl.java
- core/src/main/java/io/temporal/samples/nexusmultipleargs/handler/NexusServiceImpl.java
Show mapping Nexus operation to multiple input args
> Show mapping Nexus operation to multiple input args

- build.gradle
- core/src/main/java/io/temporal/samples/polling/infrequent/InfrequentPollingActivityImpl.java
- core/src/main/java/io/temporal/samples/polling/infrequentwithretryafter/InfrequentPollingWithRetryAfterActivityImpl.java
Switch poller sample to use `ApplicationErrorCategory`
> Switch poller sample to use ApplicationErrorCategory

- core/src/main/java/io/temporal/samples/nexuscancellation/README.MD
- core/src/main/java/io/temporal/samples/nexuscancellation/caller/HelloCallerWorkflowImpl.java
- core/src/main/java/io/temporal/samples/nexuscancellation/handler/HelloHandlerWorkflowImpl.java
Add CancellationType to nexus cancellation sample
> Add CancellationType to nexus cancellation sample

- core/src/test/java/io/temporal/samples/interceptorreplaytest/InterceptorReplayTest.java
Test that shows how to register interceptor with test env and also does replay testing
> add replayer test with worker interceptor

- README.md
- core/src/main/java/io/temporal/samples/hello/HelloSignalWithStartAndWorkflowInit.java
- core/src/main/java/io/temporal/samples/hello/README.md
- core/src/test/java/io/temporal/samples/hello/HelloSignalWithStartAndWorkflowInitTest.java
sample that shows how to use WorkflowInit to initialize workflow state if client can start workflows with both start and signalwithstart
> HelloSignalWithStartAndWorkflowInit sample
